name: Kernel CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v2

    - name: Getting Toolchain
      run: |
        sudo apt-get install lib32z1
        sudo git clone --depth 1 --branch master --single-branch https://github.com/morogoku/aarch64-cortex_a53-linux-gnueabi-GNU-6.3.0 /opt/toolchains/aarch64-cortex_a53-linux-gnueabi-GNU-6.3.0/
    - name: Building Kernel
      run: |
        make -j2 alexax_a3xelte_defconfig
        make -j64
    - name: Moving Output # CI only
      run: |
        mkdir -p /home/runner/work/output
        cp arch/arm/boot/Image /home/runner/work/output/zImage
    - name: Uploading Output
      uses: actions/upload-artifact@v2
      with:
        name: zImage
        path: /home/runner/work/output/zImage
